const products = [
  {
    category: "shoes",
    name: "Běhací tenisky",
    desc: "Růžová s kontrastními šedými a bílými detaily? Veliká paráda! Tyhle tenisky jsou další srdcová záležitost.",
    price: 1790,
    imgSrc: "running-shoes.jpg",
    imgAlt: "Běhací tenisky",
  },
  {
    category: "shoes",
    name: "Třpytivé lodičky",
    desc: "Elegantní třpyticé lodičky, které padnou skoro ke každému outfitu. Toto nesmí ve vašem šatníku chybět.",
    price: 2950,
    imgSrc: "shiny-shoes.jpg",
    imgAlt: "Třpytivé lodičky",
  },
  {
    category: "shoes",
    name: "Červené botičky",
    desc: "Extravagantní červené boty s vysokým šnerováním. V těchto botách se zá vámi budou všichni otáčet.",
    price: 6200,
    imgSrc: "red-shoes.jpg",
    imgAlt: "Červené botičky",
  },
  {
    category: "dresses",
    name: "Červené šaty",
    desc: "V barvě jahod! Krátké šaty v sytě červeném odstínu Váš šatník nekompromisně nabijí energií.",
    price: 2290,
    imgSrc: "red-dress.jpg",
    imgAlt: "Červené šaty",
  },
  {
    category: "dresses",
    name: "Květované šaty",
    desc: "Vzdušné, rozevláté a především velmi pohodlné! Tyhle šaty od dánské značky zkrátka nebudete chtít sundat.",
    price: 3100,
    imgSrc: "flower-dress.jpg",
    imgAlt: "Květované šaty",
  },
  {
    category: "dresses",
    name: "Žluté šaty",
    desc: "Žluté jako slunce! Volnější plátěné šaty s vypasovanou siluetou mají potenciál slušet opravdu každé postavě.",
    price: 4250,
    imgSrc: "yellow-dress.jpg",
    imgAlt: "Žluté šaty",
  },
  {
    category: "accessories",
    name: "Modrá kabelka",
    desc: "Efektní kožená kabelka v krásné modré barvě poskytne dostatek prostoru pro váš mobil, peněženku a další nezbytnosti.",
    price: 3590,
    imgSrc: "blue-handbag.jpg",
    imgAlt: "Modrá kabelka",
  },
  {
    category: "accessories",
    name: "Šedá vlněná šála",
    desc: "Stylová unisexová šála vyrobená ze 100% extra jemné merino vlny. Moderní, jednoduché a věčné.",
    price: 970,
    imgSrc: "grey-scarf.jpg",
    imgAlt: "Šedá vlněná šála",
  },
  {
    category: "accessories",
    name: "Brýle",
    desc: "Holky nezlobte se, já už fakt nevím, co bych si tady měl vymyslet za text. Šaty, boty a kabelky mě zcela vyčerpaly.",
    price: 1620,
    imgSrc: "glasses.jpg",
    imgAlt: "Brýle",
  },
];

export default products;
