const products = [
  {
    id: 1,
    category: "shoes",
    name: "Běhací tenisky",
    desc: "Růžová s kontrastními šedými a bílými detaily? Veliká paráda! Tyhle tenisky jsou další srdcová záležitost.",
    price: 1790,
    imgSrc: "./assets/running-shoes.jpg",
    imgAlt: "Běhací tenisky",
  },
  {
    id: 2,
    category: "shoes",
    name: "Třpytivé lodičky",
    desc: "Elegantní třpyticé lodičky, které padnou skoro ke každému outfitu. Toto nesmí ve vašem šatníku chybět.",
    price: 2950,
    imgSrc: "./assets/shiny-shoes.jpg",
    imgAlt: "Třpytivé lodičky",
  },
  {
    id: 3,
    category: "shoes",
    name: "Červené botičky",
    desc: "Extravagantní červené boty s vysokým šnerováním. V těchto botách se zá vámi budou všichni otáčet.",
    price: 6200,
    imgSrc: "./assets/red-shoes.jpg",
    imgAlt: "Červené botičky",
  },
  {
    id: 4,
    category: "dresses",
    name: "Červené šaty",
    desc: "V barvě jahod! Krátké šaty v sytě červeném odstínu Váš šatník nekompromisně nabijí energií.",
    price: 2290,
    imgSrc: "./assets/red-dress.jpg",
    imgAlt: "Červené šaty",
  },
  {
    id: 5,
    category: "dresses",
    name: "Květované šaty",
    desc: "Vzdušné, rozevláté a především velmi pohodlné! Tyhle šaty od dánské značky zkrátka nebudete chtít sundat.",
    price: 3100,
    imgSrc: "./assets/flower-dress.jpg",
    imgAlt: "Květované šaty",
  },
  {
    id: 6,
    category: "dresses",
    name: "Žluté šaty",
    desc: "Žluté jako slunce! Volnější plátěné šaty s vypasovanou siluetou mají potenciál slušet opravdu každé postavě.",
    price: 4250,
    imgSrc: "./assets/yellow-dress.jpg",
    imgAlt: "Žluté šaty",
  },
  {
    id: 7,
    category: "accessories",
    name: "Modrá kabelka",
    desc: "Efektní kožená kabelka v krásné modré barvě poskytne dostatek prostoru pro váš mobil, peněženku a další nezbytnosti.",
    price: 3590,
    imgSrc: "./assets/blue-handbag.jpg",
    imgAlt: "Modrá kabelka",
  },
  {
    id: 8,
    category: "accessories",
    name: "Šedá vlněná šála",
    desc: "Stylová unisexová šála vyrobená ze 100% extra jemné merino vlny. Moderní, jednoduché a věčné.",
    price: 970,
    imgSrc: "./assets/grey-scarf.jpg",
    imgAlt: "Šedá vlněná šála",
  },
  {
    id: 9,
    category: "accessories",
    name: "Brýle",
    desc: "Holky nezlobte se, já už fakt nevím, co bych si tady měl vymyslet za text. Šaty, boty a kabelky mě zcela vyčerpaly.",
    price: 1620,
    imgSrc: "./assets/glasses.jpg",
    imgAlt: "Brýle",
  },
];

export default products;
